services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest

    container_name: jellyfin

    networks:
      - server

    env_file:
      - path: ../environment/jellyfin.env

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - JELLYFIN_PublishedServerUrl="http://${HOST_IP}"     # [optional]

    volumes:
      - ${CONFIG}/jellyfin:/config
      - ${MEDIA}:/data

    ports:
      - ${HTTP_UI}:8096/tcp         # Unsecure Server Accesss
      - ${HTTPS_UI}:8920/tcp        # Secure Server Access    [optional]
      - ${DISCOVERY_UDP}:7359/udp   # Client Discovery        [optional]
      - ${DLNA_UDP}:1900/udp        # DLNA Server             [optional]

    restart: unless-stopped