services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    
    container_name: qbittorrent
    
    depends_on: gluetun

    network_mode: "${NETWORK}"

    env_file: ./environment/qbittorrent.env

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${UI}
      - TORRENTING_PORT=${TOR}

    volumes:
      - ${CONFIG}/qbittorrent:/config
      - ${STORAGE}:/data/torrents
    restart: unless-stopped