services:
  watchtower:

    image: containrrr/watchtower

    container_name: watchtower

    networks:
      - server

    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WATCHTOWER_CLEANUP=true
      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock